// Generated by /aidd-setup-stack
// Source: https://nextjs.org/docs/app/api-reference/config/typescript
// Next.js version: 16.3.2 | Date: 2026-08-25
import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
