// Generated by /aidd-setup-stack
// Source: https://tailwindcss.com/docs/installation/framework-guides/nextjs
// Tailwind CSS version: 4.3.3 | Date: 2026-08-25
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
